[build]
builder = "NIXPACKS"
buildCommand = "cd server && npm ci && npm run build"

[deploy]
startCommand = "cd server/dist && node index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

